const imagePool = [
  // Wedding & Engagement
  "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1515562141207-5dca3b8c0d5f?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=900&q=80",
  // Nature & Outdoor
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1469022563149-aa64dbd37720?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1495562411223-a6b0fb3ce338?auto=format&fit=crop&w=900&q=80",
  // Romantic & Couple
  "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1514539331726-15ef4d4d4d94?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1465056836643-15cea6caf04d?auto=format&fit=crop&w=900&q=80",
  // Golden Hour & Sunset
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1470229722913-7f419344ca51?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1502181851512-7cf1c4ad2f72?auto=format&fit=crop&w=900&q=80",
  // Portraits & Studio
  "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1529634597503-139d3726fed5?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",
];

const stillCategories = [
  {
    key: "boys",
    label: "Boys Portraits",
    sourceQuery: "https://www.pexels.com/search/boys%20portrait%20photography/",
    ideas: [
      "Clean profile headshot",
      "College farewell portrait",
      "Bike side pose",
      "Casual street walk",
      "Black shirt studio look",
      "Graduation smile",
      "Formal resume portrait",
      "Gym transformation photo",
      "Birthday solo frame",
      "Creator thumbnail pose",
      "Outdoor sunset portrait",
      "Traditional kurta pose",
      "Best friend duo frame",
      "Low-light cinematic look",
      "Confidence close-up",
    ],
  },
  {
    key: "girls",
    label: "Girls Portraits",
    sourceQuery: "https://www.pexels.com/search/girl%20portrait%20photography/",
    ideas: [
      "Elegant profile photo",
      "Traditional half saree pose",
      "Birthday glam portrait",
      "College farewell look",
      "Soft window light",
      "Creator cover frame",
      "Outdoor floral portrait",
      "Simple studio smile",
      "LinkedIn-ready headshot",
      "Ethnic jewellery close-up",
      "Golden hour walk",
      "Best friend duo",
      "Saree twirl frame",
      "Makeup portfolio shot",
      "Confidence portrait",
    ],
  },
  {
    key: "wedding",
    label: "Wedding",
    sourceQuery:
      "https://www.pexels.com/search/indian%20wedding%20photography/",
    ideas: [
      "Bride entry wide shot",
      "Groom welcome frame",
      "Garland exchange moment",
      "Family blessing shot",
      "Ritual close-up",
      "Couple stage portrait",
      "Parents emotional frame",
      "Reception handshake",
      "Decor wide still",
      "Jewellery detail shot",
      "Candid laugh",
      "Group family portrait",
      "Mandap top angle",
      "Exit celebration",
      "Album cover portrait",
    ],
  },
  {
    key: "prewedding",
    label: "Pre-Wedding",
    sourceQuery:
      "https://www.pexels.com/search/couple%20prewedding%20photoshoot/",
    ideas: [
      "Beach walking frame",
      "Temple steps portrait",
      "Golden hour silhouette",
      "Matching outfit pose",
      "Ring close-up",
      "Candid laugh walk",
      "Bike couple frame",
      "Traditional couple portrait",
      "Rain mood pose",
      "Garden sitting frame",
      "Cinematic wide shot",
      "Hand-hold detail",
      "Sunset hug pose",
      "City lights frame",
      "Save the date still",
    ],
  },
  {
    key: "engagement",
    label: "Engagement",
    sourceQuery: "https://www.pexels.com/search/engagement%20photography/",
    ideas: [
      "Ring ceremony close-up",
      "Couple stage smile",
      "Family blessing still",
      "Invitation-style portrait",
      "Flower shower frame",
      "Decor detail shot",
      "Parents with couple",
      "Candid guest laugh",
      "Cake table still",
      "Couple hand detail",
      "Traditional outfit pose",
      "Wide venue frame",
      "Friends group shot",
      "Welcome board photo",
      "Closing couple portrait",
    ],
  },
  {
    key: "birthday",
    label: "Birthday",
    sourceQuery:
      "https://www.pexels.com/search/birthday%20party%20photography/",
    ideas: [
      "Cake cutting moment",
      "Kid solo portrait",
      "Family with cake",
      "Decor wide shot",
      "Gift opening candid",
      "Friends group frame",
      "Parents blessing still",
      "Stage smile",
      "Balloon detail",
      "Return gift table",
      "Grandparents portrait",
      "Candid laugh",
      "Theme entry frame",
      "Dance moment",
      "Final family photo",
    ],
  },
  {
    key: "maternity",
    label: "Maternity",
    sourceQuery: "https://www.pexels.com/search/maternity%20photoshoot/",
    ideas: [
      "Mother glow portrait",
      "Couple maternity frame",
      "Hands on bump",
      "Traditional saree pose",
      "Soft window light",
      "Outdoor garden still",
      "Baby shoes detail",
      "Family blessing shot",
      "Silhouette maternity",
      "Flower crown portrait",
      "Minimal studio look",
      "Candid couple laugh",
      "Seated elegant pose",
      "Golden hour profile",
      "Album cover still",
    ],
  },
  {
    key: "baby",
    label: "Baby Shoot",
    sourceQuery: "https://www.pexels.com/search/baby%20photoshoot/",
    ideas: [
      "Newborn basket still",
      "Tiny hands close-up",
      "Baby smile portrait",
      "Parent hands frame",
      "Naming ceremony portrait",
      "Toy theme still",
      "Sleeping baby shot",
      "Sibling with baby",
      "Grandparent blessing",
      "Soft blanket frame",
      "Milestone month photo",
      "Cake smash still",
      "Family cuddle shot",
      "Traditional baby outfit",
      "Album cover close-up",
    ],
  },
  {
    key: "reels",
    label: "Reels And Creators",
    sourceQuery:
      "https://www.pexels.com/search/content%20creator%20photoshoot/",
    ideas: [
      "Hook pose thumbnail",
      "Phone-in-hand frame",
      "Product reveal still",
      "Talking reel cover",
      "Dance reel freeze",
      "YouTube banner photo",
      "Podcast portrait",
      "Cafe creator look",
      "Street fashion still",
      "Behind the scenes",
      "Brand launch frame",
      "Fitness reel cover",
      "Makeup reel still",
      "Tech creator portrait",
      "Announcement poster frame",
    ],
  },
  {
    key: "business",
    label: "Business And Shops",
    sourceQuery:
      "https://www.pexels.com/search/small%20business%20photography/",
    ideas: [
      "Shop owner portrait",
      "Product shelf still",
      "Food plate close-up",
      "Team photo",
      "Salon service frame",
      "Boutique outfit still",
      "Customer service shot",
      "Office headshot",
      "Menu item photo",
      "Brand poster frame",
      "Tool detail shot",
      "Storefront wide image",
      "Packaging close-up",
      "Founder profile",
      "Launch announcement still",
    ],
  },
  {
    key: "editing",
    label: "Editing Ideas",
    sourceQuery: "https://www.pexels.com/search/photo%20editing%20photography/",
    ideas: [
      "Clean color correction",
      "Skin retouch sample",
      "Cinematic color grade",
      "Album layout page",
      "Before-after portrait",
      "Background cleanup",
      "Reel cover design",
      "Invitation poster",
      "Birthday poster edit",
      "Wedding teaser cover",
      "Product cutout",
      "Light leak style",
      "Black and white finish",
      "Warm film tone",
      "Social media crop set",
    ],
  },
  {
    key: "events",
    label: "Events And Functions",
    sourceQuery: "https://www.pexels.com/search/event%20photography/",
    ideas: [
      "Stage wide shot",
      "Chief guest portrait",
      "Lamp lighting moment",
      "Audience candid",
      "Anchor speaking frame",
      "Award receiving still",
      "Team group photo",
      "Decor detail",
      "Food counter still",
      "Entry welcome frame",
      "Dance performance shot",
      "Crowd reaction",
      "Banner photo",
      "Sponsor wall portrait",
      "Closing group frame",
    ],
  },
  {
    key: "nature",
    label: "Nature & Outdoor",
    sourceQuery:
      "https://www.pexels.com/search/nature%20outdoor%20photography/",
    ideas: [
      "Forest green frame",
      "Mountain peak vista",
      "Waterfall misty shot",
      "Lake reflection portrait",
      "Golden field walk",
      "Garden flower frame",
      "Sunset silhouette",
      "Misty morning mood",
      "Tree canopy frame",
      "River bank portrait",
      "Meadow dance moment",
      "Sky clouds detail",
      "Stone pathway walk",
      "Natural light portrait",
      "Adventure spirit frame",
    ],
  },
  {
    key: "romantic",
    label: "Romantic & Couple Moments",
    sourceQuery:
      "https://www.pexels.com/search/romantic%20couple%20photoshoot/",
    ideas: [
      "Sunset couple silhouette",
      "Close forehead touch",
      "Hand-in-hand walk",
      "Candlelit romantic gaze",
      "Flower garden embrace",
      "Rain moment together",
      "Rooftop city lights",
      "Beach waves embrace",
      "Balcony sunset frame",
      "Forest romantic walk",
      "Window light moment",
      "Slow dance freeze",
      "Ring exchange closeup",
      "Matching outfit pose",
      "Future together frame",
    ],
  },
  {
    key: "goldenhour",
    label: "Golden Hour Magic",
    sourceQuery: "https://www.pexels.com/search/golden%20hour%20photography/",
    ideas: [
      "Soft sunlight portrait",
      "Backlit hair glow",
      "Warm tone couple frame",
      "Evening walk golden glow",
      "Sky paint portrait",
      "Silhouette with glow",
      "Warm skin tone frame",
      "Natural shadows detail",
      "Golden dust particles",
      "Flare lens portrait",
      "Amber light background",
      "Sunset reflection portrait",
      "Dreamy warm tones",
      "Cinematic color grade",
      "Memory album worthy frame",
    ],
  },
];

function getStills() {
  let serial = 1;
  return stillCategories.flatMap((category, categoryIndex) =>
    category.ideas.map((title, ideaIndex) => ({
      id: `MLS-STILL-${String(serial++).padStart(3, "0")}`,
      category: category.key,
      categoryLabel: category.label,
      title,
      imageUrl: imagePool[(categoryIndex + ideaIndex) % imagePool.length],
      sourceQuery: category.sourceQuery,
      prompt: `${category.label}: ${title}`,
    })),
  );
}

module.exports = { stillCategories, getStills };
